# Generated by Django 4.1.3 on 2022-12-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing_pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
