# Generated by Django 4.1.3 on 2023-05-10 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='images')),
                ('status', models.TextField(blank=True, null=True)),
                ('City', models.CharField(blank=True, max_length=30, null=True)),
                ('Lives', models.CharField(blank=True, max_length=10, null=True)),
                ('Interested', models.CharField(blank=True, max_length=20, null=True)),
                ('Relationship', models.CharField(blank=True, max_length=20, null=True)),
                ('Looking', models.CharField(blank=True, max_length=10, null=True)),
                ('Height', models.IntegerField(blank=True, null=True)),
                ('Education', models.CharField(blank=True, max_length=20, null=True)),
                ('Favoutite_music', models.CharField(blank=True, max_length=30, null=True)),
                ('Favoutite_movie', models.CharField(blank=True, max_length=30, null=True)),
                ('Favoutite_Books', models.CharField(blank=True, max_length=30, null=True)),
                ('Favoutite_TV_shows', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
