# Generated by Django 4.1.3 on 2023-05-10 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account_of_User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.PositiveIntegerField(default=0)),
                ('visitor', models.PositiveIntegerField(default=0)),
                ('friend_list', models.ManyToManyField(blank=True, related_name='friend_list', to='Account_of_User.userprofile')),
                ('send_friend_request', models.ManyToManyField(blank=True, related_name='send_friend_request', to='Account_of_User.userprofile')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Account_of_User.userprofile')),
            ],
        ),
    ]
