# Generated by Django 4.1.3 on 2023-05-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_of_User', '0004_notifiy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('send', 'send'), ('accepted', 'accepted'), ('like', 'like'), ('visitor', 'visitor')], max_length=20),
        ),
    ]
