# Generated by Django 4.1.3 on 2023-05-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_of_User', '0005_alter_relationship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(default='images/default.jpg', upload_to='images'),
        ),
    ]
